In [3]:
import pandas as pd
import numpy as np
from statsmodels.discrete.discrete_model import Probit
import statsmodels.api as sm

In [4]:
df=pd.read_stata('nels_small.dta')

In [5]:
df.head()

psechoice  hscath  grades  faminc  famsiz  parcoll  female  black
0          2       0    9.08    62.5       5        0       0      0
1          2       0    8.31    42.5       4        0       1      0
2          3       0    7.42    62.5       4        0       1      0
3          3       0    7.42    62.5       4        0       1      0
4          3       0    7.42    62.5       4        0       1      0

In [6]:
df.isnull().any()

psechoice    False
hscath       False
grades       False
faminc       False
famsiz       False
parcoll      False
female       False
black        False
dtype: bool

# a)

In [7]:
df["COLLEGE"]=np.where(df.psechoice==1,0,1)

In [8]:
len(df[df.COLLEGE==1])*100/len(df)

77.8

(b)	Estimate a probit model explaining COLLEGE, using as explanatory variables GRADES, 
13-point scale with 1 indicating the highest grade and 13 the lowest; FAMINC, gross family income in $1,000 increments; 
FAMSIZ, number of family members; PARCOLL = 1 if the most educated parent had a college degree; FEMALE = 1 if female; 
and BLACK = 1 if black. Are the signs of the estimated coefficients consistent with your expectations? Explain. 
Are the estimated coefficients statistically significant?

In [13]:
Y=df.COLLEGE
X=df.drop(["COLLEGE","psechoice",'hscath'],axis=1)

In [14]:
probit = sm.Probit(Y,X)
result = probit.fit()
result.summary()

Optimization terminated successfully.
         Current function value: 0.468360
         Iterations 6


<class 'statsmodels.iolib.summary.Summary'>
"""
                          Probit Regression Results                           
==============================================================================
Dep. Variable:                COLLEGE   No. Observations:                 1000
Model:                         Probit   Df Residuals:                      994
Method:                           MLE   Df Model:                            5
Date:                Wed, 17 Apr 2019   Pseudo R-squ.:                  0.1153
Time:                        18:01:46   Log-Likelihood:                -468.36
converged:                       True   LL-Null:                       -529.43
                                        LLR p-value:                 1.107e-24
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
grades        -0.1035      0.017     -6.254      0.000      -0.136      -0.071
faminc         0.0086      0.002      4.860      0.000       0.005       0.012
famsiz         0.1624      0.030      5.356      0.000       0.103       0.222
parcoll        0.6601      0.131      5.026      0.000       0.403       0.918
female         0.3249      0.092      3.550      0.000       0.146       0.504
black          0.5637      0.211      2.677      0.007       0.151       0.976
==============================================================================
"""

As expected all the variables are statistically significant and all variables have positive coefficients except grades

The ones that were not expected by me are:

-black, meaning that blacks are more prone to go to college than not blacks

-family size meaning that the bigger the family the higher the chance to go to college

-grade has a negative one as the smaller the number the better the grade

# c)

In [23]:
sample=[5,df.faminc.mean(),5,1,1,1]
result.predict(sample)

array([0.98889305])

In [22]:
sample=[10,df.faminc.mean(),5,1,1,1]
result.predict(sample)

array([0.96156268])

# d)

In [21]:
sample=[10,df.faminc.mean(),5,1,1,0]
result.predict(sample)

array([0.88598708])

In [24]:
sample=[10,df.faminc.mean(),5,1,0,0]
result.predict(sample)

array([0.81073187])

# e)

In [25]:
X_new=X.drop(["parcoll","black",'female'],axis=1)

In [26]:
probit = sm.Probit(Y,X_new)
result = probit.fit()
result.summary()

Optimization terminated successfully.
         Current function value: 0.491659
         Iterations 6


<class 'statsmodels.iolib.summary.Summary'>
"""
                          Probit Regression Results                           
==============================================================================
Dep. Variable:                COLLEGE   No. Observations:                 1000
Model:                         Probit   Df Residuals:                      997
Method:                           MLE   Df Model:                            2
Date:                Wed, 17 Apr 2019   Pseudo R-squ.:                 0.07134
Time:                        18:34:25   Log-Likelihood:                -491.66
converged:                       True   LL-Null:                       -529.43
                                        LLR p-value:                 3.958e-17
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
grades        -0.0978      0.016     -6.263      0.000      -0.128      -0.067
faminc         0.0125      0.002      7.774      0.000       0.009       0.016
famsiz         0.1868      0.029      6.486      0.000       0.130       0.243
==============================================================================
"""

the remaning variables were and stay siginificant, the direction of their effect also is the same